export default [
    {
        id:1,
        name:'programming',
        icon:'/coding.png',
        prompt:''
    },
    {
        id:2,
        name:'Health',
        icon:'/medical-team.png',
        promp:''
    },
    {
        id:3,
        name:'creative',
        icon:'/design-thinking.png',
        promp:''
    },
]